### ISSUE TITLE
Weights not added to copy command

### ISSUE THREAD

**Issue by Dablakbandit** [RJ1002/pollmaster#52]
First off thanks for porting the bot :)

**Describe the bug**
Weights are not copied when using /copy into the /cmd command

**To Reproduce**
1. Use the /advanced poll creation
2. Under weights add a weight to a poll
3. Use /copy on that poll
4. Paste the command and run to create a copy of the poll

**Expected behavior**
Weights to be included in the copied poll

**Screenshots**
Example poll:
![image_2024-03-03_102311636](https://github.com/RJ1002/pollmaster/assets/5752611/d82a3ef2-853b-41c4-a7ba-6e7e3ccfedab)

Command missing weights:
![image_2024-03-03_102347572](https://github.com/RJ1002/pollmaster/assets/5752611/8869e2b8-e0ed-4708-b878-4cd3010de182)

Using Desktop

**Comment by RJ1002** [comment]
so it looks like it was never added to the /copy command at all. so I will look into adding it.

**Comment by RJ1002** [comment]
This feature has been added. https://github.com/RJ1002/pollmaster/commit/ce60468eaf64b316104a4451b06323ddba229390
